version: "3.8"

services:
  pgdb:
    image: postgres
    env_file:
      - .env
    volumes:
      - .:/docker-entrypoint-initdb.d
      - data:/var/lib/postgresql/data
    expose:
      - 5432:5432
  fastapi:
    build: .
    command: uvicorn main:app --reload --host 0.0.0.0
    restart: always
    env_file:
      - .env
    volumes:
      - .:/auth
    ports:
      - "8000:8000"
    depends_on:
      - pgdb
volumes:
  data:
